### ISSUE TITLE
Decidere un modo per gestire le versioni, in particolare quella in produzione e quella in test

### ISSUE THREAD

**Issue by phauly** [kercos/HiSTORICCacciaAlTesoro#16]
il ticket era nato da come come "Inserire versione delle tabelle come parametro in tutto il codice" ma in realta' la questione e' piu' generale

@kercos diceva in altro ticket

>No la versione delle tabelle è una cosa importante, si potrebbe mettere un parametro di versionamento per assicurarsi la compatibilità tra codice e tabelle e comunque scrivere del codice per controllare che la tabella non abbia errori.

Quindi questo ticket e' per coordinare la modifica "Inserire versione delle tabelle come parametro in tutto il codice", e' una modifica "piccola" ma che va pensata bene e inserita nei (molti, immagino) posti dove deve essere inserita. Al momento io non avrei la minima idea del modo migliore di fare questa modifica in tutto il codice ....

**Comment by kercos** [comment]
Dobbiamo avere un codice unico di versionamento (e.g., 0.1.0) per assicurarsi compatibilità tra codice e airtable.

Nel controllo automatico che l'airtable non abbia errori dobbiamo aggiungere un controllo che la versione sia compatibile con quella del codice. Qua il codice (incompleto) per controllo automatico di airtable:
https://github.com/kercos/HiSTORICCacciaAlTesoro/blob/master/airtable_check.py

Nel codice basterebbe una variable qua:
https://github.com/kercos/HiSTORICCacciaAlTesoro/blob/56518c2568d373180ac81adb24d6a650e59f67e6/params.py#L2

In aritable in ogni caccia al tesoro va messa una variable nella tabella `Settings`
![image](https://user-images.githubusercontent.com/2836492/113247397-f16c9500-92f5-11eb-96f5-3b8437b99eff.png)

**Comment by phauly** [comment]
tipo usano tutti le stesse tabelle airtable? se volessimo cambiare formato di tabelle ad esempio dovremmo fare un branch, mettere il codice del branch nell'ambiente di test, testarlo a manetta e solo dopo fare commit del branch sul main e a quel punto mettere quel codice anche in abiente production? quindi il bot di test conviene che faccia sempre girare il codice di un branch? e' cosi'?

**Comment by kercos** [comment]
@phauly Si dovremmo un po' alla volta trovare una quadra per come procedere su questo punto. 
Non so bene quale sia la metodologia consigliata in questo caso. Provo ad abbozzare una proposta poi la raffiniamo e quando  definitiva le possiamo mettere nella descrizione del cartellino in alto, e se occorre procedere con delle azioni possiamo aprire nuovi cartellini.

Questione **branch**:
- Il codice di produzione è associato alla branch `master`
- Il codice di test è associato alla branch `dev`
- Ogni modifica del codice legata ad un cartellino (issue) viene fatta su una branch temporanea (che porta il nome dell cartellino), va testata con il bot di test e mergiata sulla branch `dev`
- Quando si decide di rendere una modifica definitiva (mandarla in produzione) bisogna mergiare le modifiche in `master`.
- Per tenere traccia di dove sono le branch usare il [grafico network di github](https://github.com/kercos/HiSTORICCacciaAlTesoro/network): 

Questione **versioni**:
Dobbiamo introdurre una variabile nel codice per tenere traccia della versione (e.g., 1.2.3).  La versione si deve poter visualizzare dal bot tramite comando o da interfaccia admin (quando verrà implementata). Ogni modifica al codice comprta un cambio di versione. Possiamo valutare di usare le tag nel network per marcare le versioni nel grafico [network](https://github.com/kercos/HiSTORICCacciaAlTesoro/network).
Ogni cambio di versione può causare un'incompatibilità con alcune basi di airtable (cacce al tesoro). Pertanto è necessario
- inserire una variable in Setting in ogni caccia che indichi l'ultima versione del codice con cui la caccia è stata testata
- inserire una tabella nella base CONFIG per tenere traccia delle diverse versioni indicando solo quelle che richiedono una modifica alle tabelle e specificare quali modifiche apportare.

**Comment by phauly** [comment]
L'hai scritto con una precisione sconcertante, accipicchia, ho capito tutto, io non riusciro' mai ad essere cosi' chiaro e preciso (ma almeno capisco quello che dici ;)

non mi e' chiarissimo questo
> inserire una tabella nella base CONFIG per tenere traccia delle diverse versioni indicando solo quelle che richiedono una modifica alle tabelle e specificare quali modifiche apportare.
intendi che in config scrivi qualcosa tipo
* versione 1.2.3 | le tabelle devono avere le colonne x, y, z, NEXT e gli asterischi devono essere in numero pari ecc ecc
* versione 1.2.4 | le tabelle devono avere le colonne x, y, z, NEXT e gli asterischi devono essere in numero pari ma rispetto a prima nel campo NEXT c'e' solo un valore booleano che dice se la tappa successiva e' la seguente
 
Cioe' intendi che nella tabella listiamo tutte le condizioni? non e' un po' troppo dettagliato (e in fin dei conti inutile nel senso che non andremo mai a guardare questa tabella?)
O forse intendi solo che mettiamo i nomi delle colonne?

E comunque non ci serve avere retrocompatibilita', ovvero NON saremo mai nel caso di dover far girare la caccia di Calavino con il codice vecchio (come era al tempo di Calavino) e con l'airtable per come era allora. Insomma, dovessimo anche rifare la caccia di Calavino e volessimo rifarla con tutte le stesse tappe, credo che la strada migliore sarebbe di creare una nuova tabella (compatibile con l'ultima versione del codice) e copiaincollare a mano le tappe, eventualmente adattando campi o togliendo/inserendo campi.

Insomma credo di non avere capito bene questo punto ma tutto il resto si'. E credo pure di non essere stato molto chiaro nel dire cosa non ho capito ;)

**Comment by kercos** [comment]
Bene, sono contento che la spiegazione sia abbastanza chiara. Scrivere aiuta a strutturare meglio le cose.
Per quanto riguarda la tabella VERSIONS nella base CONFIG di Airtable, non è necessario inserire tutte le condizioni ma solo le modifiche rispetto alla versione precedente.
Ad esempio supponendo che la versione attuale sia 1.0.0 avremmo
1.0.0 | Inizio versionamento
1.1.0 | Nella tabella "Missioni" è ora possible avere inserire in NEXT missioni di qualsiasi categoria, incluse ripetizioni - questo relativo alla issue #19
1.2.0 | Nella tabella "Survey" se una riga è di tipo "Open" il field "RISPOSTE" può essere vuoto (per rendere la risposta obbligatoria togliendo il "Salta") - questo relativo alla issue #21 
1.3.0 | Nella tabella "Missioni" la colonna X viene rinominata in Y

In questi esempi ho usato la convenzione che nel versionamento X.Y.Z le modifiche del codice che hanno ripercussione su Airtable coinvolgono il campo Y. Altre modifiche che non hanno ripercussione su Airtable (ad esempio, introduzione di interfaccia amministratore)  coinvolgono il campo Z. Questo forse potrebbe aiutarci di tenere le modifiche un po' più ordinate.

**Comment by kercos** [comment]
Sarebbe utile trovare un modo per fare un deploy automatico sul bot quando si fanno modifiche al repository. Non è semplicissimo ma dovrebbe essere fattibile. 
1. Come prima cosa bisognerebbe sistemare la questione delle variabili segrete attualmente nascoste nel file `key.py` (non versionato). La soluzione forse più semplice è quella di utilizzare environmental variables e dotenv. Vedi https://www.nylas.com/blog/making-use-of-environment-variables-in-python/
2. Usare Cloud Run di google per fare `Continuous deployment from Git using Cloud Build` (vedi https://cloud.google.com/run/docs/continuous-deployment-with-cloud-build). Questo dovrebbe essere compatibile con le `environment variables` (vedi https://cloud.google.com/run/docs/configuring/environment-variables).

**Comment by kercos** [comment]
@phauly @mirko-nespoli buone notizie, sono riuscito a far funzionare i deploy automatici da github. L'ho testato su una branch `refactoring` dove ho fatto anche un po' di pulizia. Questo ci potrà consentire di testare e rendere modifiche effettive più velocemente e sistematicamente. Magari organizziamo una call dopo la caccia per coordinarci.

**Comment by kercos** [comment]
@phauly @mirko-nespoli chiudo questo issue

**Comment by kercos** [comment]
ops, chiuso quello sbagliato

**Comment by kercos** [comment]
Ricapitolando:
Ho creato due GitHub actions per fare deploy atuomatici:
1. Sul bot di `test` quando viene fatta una push su una branch che si riferisce ad un `issue xx` (il nome della branch deve avere `issue` nel nome).
2. Sub bot ufficiale di `production` quando viene fatta una push su `master`. Questo include anche quando una pull request delle branch `issue xx` vengono mergiate su master.

Su Airtable nella base CONFIG ho aggiunto la tebella VERSIONS per tracciare le modifiche che devono essere fatte alle cacce quando si passa da una versione all'altra. Il codice ha version X.Y.Z ma solo le modifiche in X.Y sono quelle che richiedono modifiche alle tabelle delle cacce su airtable. 

TODO:
- aggiungere in ogni caccia nella tabella `Settings` una riga `VERSION` con 0.1 (vedi esempio `caccia di prova`)

![image](https://user-images.githubusercontent.com/2836492/117021069-f9bf5200-ad31-11eb-9e5e-54563319187c.png)
![image](https://user-images.githubusercontent.com/2836492/117024851-55d7a580-ad35-11eb-87af-4594a1048906.png)
