### ISSUE TITLE
Inoltro errori

### ISSUE THREAD

**Issue by mirko-nespoli** [kercos/HiSTORICCacciaAlTesoro#17]
Inviare gli errori del codice anche a Mirko e Paolo se interessato

**Comment by phauly** [comment]
ti riferisci a errori in airtable, vedi #11 

o ad errori fatti dai partecipanti nelle risposte, vedi #6?

o altro? ;)

**Comment by mirko-nespoli** [comment]
Mi riferisco ad issue 11 quindi chiudo questo
