### ISSUE TITLE
Non funziona il prossima tappa

### ISSUE THREAD

**Issue by mirko-nespoli** [kercos/HiSTORICCacciaAlTesoro#19]
Non so se ho sbagliato io, ma mettendo il nome della tappa che si vuole mettere come next dà errore e non parte

**Comment by kercos** [comment]
Hai controllato eventuali spazi? 
Riusciresti a fare una copia della caccia che da errore e rinominarla (e.g. ERRORE_NEXT) e menzionarla qua così quando ho tempo di risolvere il problema posso riprodurlo. Non vorrei che per modifiche o altro il problema si perda e non sia più riproducibile.

**Comment by mirko-nespoli** [comment]
❗️ Exception Traceback (most recent call last):
  File "/workspace/main_exception.py", line 10, in exception_reporter_wrapper
    func(*args, **kwargs)
  File "/workspace/main_exception.py", line 26, in report_exception_in_thread
    func(*args,  **kwargs)
  File "/workspace/ndb_utils.py", line 8, in client_context_wrapper
    return func(*args, **kwargs)
  File "/workspace/bot_telegram_dialogue.py", line 931, in deal_with_request
    repeat_state(p, message_obj=message_obj)
  File "/workspace/bot_telegram_dialogue.py", line 68, in repeat_state
    method(user, message_obj, **kwargs)
  File "/workspace/bot_telegram_dialogue.py", line 110, in state_INITIAL
    game.reset_game(p, hunt_password)
  File "/workspace/game.py", line 184, in reset_game
    missioni = get_random_missioni(p, airtable_game_id, mission_tab_name, initial_cat)
  File "/workspace/game.py", line 108, in get_random_missioni
    assert next(round_robin_cat) == next_mission_cat
AssertionError

Questo è l'errore che mi avevi rigirato a riguardo, provo a replicarlo in quella caccia di prova che ho creato

**Comment by mirko-nespoli** [comment]
Ho appena provato a replicarlo nella caccia di prova togliendo gli spazi, e mi dà errore
Ho inserito il nome della missione che vorrei fosse quella seguente ad una (in esempio family card a seguire googlamap) ma non parte

**Comment by kercos** [comment]
@mirko-nespoli ho riprodotto il problema nella caccia di prova. 

Il problema è dovuto al fatto che se hai diverse categorie di missioni (ad esempio INDOVINELLO e GIOCO) il sistema cerca di alternarle. Per evitare di forzare il sistema ad avere due missioni dello stesso tipo con NEXT, avevo attivato un controllo che generava questo errore. Abbiamo quindi due soluzioni:

1. togliere il controllo e quindi acconsentire di avere più missioni dello stesso tipo consecutive
2. mantenere il controllo e quando si verifica modificare il NEXT manualmente (in modo da preservare l'alternanza)

Penso che la 1 sia la cosa più semplice (e non mi sembra abbia possibili complicazioni) ma fammi sapere cosa ne pensi.

**Comment by mirko-nespoli** [comment]
L'alternanza gioco/indovinello al momento non ha molto senso e non la sfruttiamo, mentre il Next risulterebbe utile
Direi la numero 1, l'accendo

**Comment by phauly** [comment]
Sono d'accordo con la 1.

Teniamo anche presente che l'intero metodo andra' modificato (sicuro se facciamo cacce permanenti) come da discutere in #10 pero' come fix a breve la 1 mi sembra perfetta!

**Comment by kercos** [comment]
@mirko-nespoli ho fatto le modifiche e aggiornato il bot di prova. Fai alcune prove con NEXT e verifica che tutto funzioni. Se ci sono problemi segnalameli qua, se no puoi premere il pulsante verde MERGE nella pull request #24 che ti ho assegnato per rendere definitive le modifiche nella branch `dev` (vedi discussione #16 con @phauly).

**Comment by mirko-nespoli** [comment]
Ho provato il next ma credo abbia ancora problemi in quanto non parte

**Comment by mirko-nespoli** [comment]
Ok l'ho provato sul bot di test e mi pare funzionare correttamente in maniera indifferente dal tag CATEGORIA. Ho provato un pò a fare incrociati tra indovinello e gioco e concatenati ed è andato bene. Mi pare che questo sia ok

**Comment by mirko-nespoli** [comment]
Ok ci siamo, ho provato sul bot di test e funziona. Sia su caccia prova che cisvfiab
Ho provato a incrociare indovinello e giochi e concatenare altre cose, piuttosto che mettere next e altra finale ed è andato
Questo direi che ci siamo

**Comment by kercos** [comment]
@mirko-nespoli puoi premere il pulsante verde MERGE nella pull request #24 che ti ho assegnato per rendere definitive le modifiche nella branch dev (vedi discussione #16 con @phauly).

**Comment by mirko-nespoli** [comment]
Forse ho fatto

**Comment by kercos** [comment]
@mirko-nespoli @phauly fatto il deploy in production

**Comment by mirko-nespoli** [comment]
Stasera ricontrollo bene che sia ok anche in produzione, poi si può testare il reinoltro gps
