### ISSUE TITLE
Aprire ad eventuali validatori

### ISSUE THREAD

**Issue by mirko-nespoli** [kercos/HiSTORICCacciaAlTesoro#20]
Trovare un modo efficace per aprire la caccia ad eventuali tester esterni senza dover per forza attivarla

**Comment by phauly** [comment]
Nel breve (ovvero senza modifiche software), quali sono le controindicazioni di farli admin per un tempo limitato (a parte il rischio di non ricordarci di toglierli dagli admin)? Chiedo perche' non ricordo se gli admin abbiano funzioni "distruttive" o invadenti la privacy o pericolose e se si' quali.

**Comment by kercos** [comment]
La cosa migliore sarebbe centralizzare tutto nella base CONFIG, aggiungendo nella tabella Managers eventuali persone esterne a hiSTORIC e andare a specificare in ogni caccia quali sono le persone che hanno controllo su ogni caccia. 
@phauly rispondendo alla tua domanda, gli amministratori rispetto alle persone normali hanno i seguenti poteri:
- testare una caccia che non è attiva
- accedere ai comandi speciali (ora specificati nell'area admin del bot=

**Comment by kercos** [comment]
@mirko-nespoli @phauly questa è pronta, non appena #52 è approvata la metto sul bot di test
