### ISSUE TITLE
Togliere skip da questionario finale

### ISSUE THREAD

**Issue by mirko-nespoli** [kercos/HiSTORICCacciaAlTesoro#21]
Nel questionario post gioco se non vengono messi bottoni si blocca. Sarebbe comodo poter togliere lo skip ed obbligarli a rispondere testualmente qualsiasi cosa

**Comment by phauly** [comment]
Al momento non ricordo e non ho voglia di fare tutta una caccia per vederlo. Riesci ad aggiungere qui uno screenshot?

**Comment by mirko-nespoli** [comment]
![skip_survey](https://user-images.githubusercontent.com/19323703/114912545-683e7d80-9e20-11eb-8963-f289e1f09c37.PNG)

Non so se è allegata giusta così, comunque in pratica nel sondaggio finale, la colonna Risposta non può essere vuota anche se il type è open quindi domanda aperta, altrimenti si blocca. Sarebbe comodo poter aver domande aperte alle quali devono per forza rispondere (che se poi rispondo Pippo amen per dire, però rispondo :D )

**Comment by phauly** [comment]
Ho testato

Quindi se la cella e' vuota e' una cella obbligatoria

Se invece c'e' "Salta" e' una cella opzionale.

Corretto?

Se si', lo scrivo nel vademecum e clicco il pulsante atomico! ;)

![image](https://user-images.githubusercontent.com/33067/122046598-645ab780-cddf-11eb-877f-89cc87a2a593.png)

**Comment by kercos** [comment]
@phauly si corretto, con l'unica precisazine che SALTA non è una string predefinita e può essere sostituita con qualsiasi altra stringa che diventerà un pulsante nel bot (e la risposta alla domanda che verrà salvata se viene premuto).

**Comment by phauly** [comment]
ottimo. scritto nel vademecum. clicco
