### ISSUE TITLE
move ux to code

### ISSUE THREAD

**Issue by kercos** [kercos/HiSTORICCacciaAlTesoro#47]
Attualmente tutte le stringhe (UX) del bot sono nella tabella UX della base CONFIG di airtable. Sarebbe importante spostarla assieme al codice, dato che le due cose vanno a braccetto: spesso abbiamo bisogno di modifiche a UX quando facciamo modifiche al codice. Tenerla in Airtable ci impedisce di avere UX diverse nei bot test/produzione.

**Comment by phauly** [comment]
ha anche il vantaggio che i controlli sulle stringhe non sono piu' (molto) necessari.

pero' il difetto e' che se vogliamo fare una modifica al volo per una caccia specifica, senza di te (o magari me in futuro o mirko) non riusciamo. sbaglio? ad esempio per cuori edition o cisv abbiamo dovuto mettere un messaggio specifico. sbaglio?

**Comment by kercos** [comment]
Si @phauly come discusso abbiamo aggiustato con https://github.com/kercos/HiSTORICCacciaAlTesoro/issues/52
