### ISSUE TITLE
UX override

### ISSUE THREAD

**Issue by kercos** [kercos/HiSTORICCacciaAlTesoro#52]
Dare la possibilità di cambiare qualsiasi stringa definita nell'UX json nella UX della caccia.

**Comment by kercos** [comment]
@mirko-nespoli pronta per essere testata.
Vedi dettagli su modifiche versione in Airtable. Controlla anche che sia chiaro come il flag RESET_HUNT_AFTER_COMPLETION vada a influenzare il comportamento del bot (e i messaggi che vengono visualizzati alla fine della caccia e dopo il messaggio terminate).
![image](https://user-images.githubusercontent.com/2836492/117563634-27b1e700-b0e2-11eb-93e0-f991c7b5b101.png)

**Comment by kercos** [comment]
@mirko-nespoli quando hai testato e tutto è ok clicca sul link qua sopra dove dice
![image](https://user-images.githubusercontent.com/2836492/117574147-b2acd480-b116-11eb-85f8-79044fbf0fb3.png)
e clicca su Merge

**Comment by mirko-nespoli** [comment]
Mi risulta difficile da testare in quanto non riesco a recuperare in autonomia dal codice tutte le possibili VAR da modificare. Riesci a farmi avere una lista?
Anche a regime, come possiamo sapere quali valori cambiare come si chiamano?

**Comment by kercos** [comment]
@mirko-nespoli ottima domanda. Ho aggiornato descrizione dell'update in airtable VERSIONS specificando l'url nel codice dove trovare le stringhe (https://github.com/kercos/HiSTORICCacciaAlTesoro/tree/master/ux). 
![image](https://user-images.githubusercontent.com/2836492/119429690-4652e780-bd4a-11eb-85ba-b055eee08912.png)

**Comment by mirko-nespoli** [comment]
Se la tabella UX è vuota, dà errore
Non riesco a fare l'overwright dei bottoni, anche se questo per me è un problema secondario in quanto potrebbe non essere necessario
