### ISSUE TITLE
Gruppo di notifica specifico per ogni caccia

### ISSUE THREAD

**Issue by kercos** [kercos/HiSTORICCacciaAlTesoro#54]

**Comment by phauly** [comment]
L'idea e' che ci sia modo si speficare, per ogni caccia, quale e' il gruppo in cui arrivano le notifiche sull'attivita' dei partecipanti.

Al momento ce ne e' solo uno che e' "hiSTORIC - Notifiche Net1".

In tabella Config New e' gia' predisposta questa cosa, credo, sotto "Notifications"
![image](https://user-images.githubusercontent.com/33067/119901096-c002f500-bf45-11eb-932a-0eb163af2ccd.png)

**Comment by kercos** [comment]
Corretto, bisogna cambiare nella tabella `HUNTS` della base `CONFIG` la colonna `Notify_Group` che ora è un flag ma dovrà diventare un link ad una riga della tabella `Notifications` (e ovviamente adattare il codice di conseguenza).
