### ISSUE TITLE
Avere un modo per sapere per ogni tappa quanti e quali errori vengono fatti (quanto la tappa richiede in media ...)

### ISSUE THREAD

**Issue by kercos** [kercos/HiSTORICCacciaAlTesoro#6]
https://github.com/kercos/HiSTORICCacciaAlTesoro/blob/e80b638e9901fcef814af1400a09ba8fdecdb274/airtable_utils.py#L64

**Comment by kercos** [comment]
Paolo mi sembra che abbia implementato già qualcosa per ricavare statistiche sulle risposte sbagliate.

**Comment by phauly** [comment]
ecco il codice che avevo scritto

```
import json
import collections

d1 = json.load(open('errori_2021_02_13.txt'))
d2 = json.load(open('errori_2021_02_14.txt'))
# merge the two dicts of lists
d3 = {}
for k in d1.keys():
    d3.update( {k : []} )
    for i in d1[k]:
        d3[k].append(i)
    for j in d2[k]:
        d3[k].append(j)

print("ERRORI piu' frequenti (Almeno 5 volte)")
for tappa in d3:
    counter = collections.Counter(d3[tappa])
    print(f'TAPPA = {tappa}')
    print(f'  ERRORI TOTALI = {sum(counter.values())}')
    for (error, freq) in counter.most_common(5):
        print(f'   ERRORE = {error}   (con frequenza = {freq})')


print("\n\nTUTTI GLI ERRORI (anche quelli poco frequenti, ad esempio occorsi solo una volta)")
for tappa in d3:
    counter = collections.Counter(d3[tappa])
    print(f'TAPPA = {tappa}')
    print(f'  ERRORI TOTALI = {sum(counter.values())}')
    for (error, freq) in counter.most_common():
        print(f'   ERRORE = {error}   (con frequenza = {freq})')
```

**Comment by phauly** [comment]
Dove avrebbe senso averlo?
* come comando dentro il bot solo per admin (ma bruttissimo avere una lunga lista di errori da un chatbot, inoltre va tenuto presente che con le cacce permanenti, se avremo 50 o 100 tappe avremo una lista di errori per ogni tappa)
* come uno script indipendente che ti manda le info per email (da far girare con un cron ad esempio che una volta al mese manda questa email)
* come uno script indipendente che crea le info dentro una tabella airtable (aggiorna la tabella anche ogni settimana ad esempio, ma il rischio e' che nessuno lo guardi, forse meglio un interrupt via email una volta ogni tanto? inoltre occhio ad usare airtable solo per cose veramente utili per evitare di arrivare presto a saturare i limiti dell'account free)

Se non ci sono altre idee, ad ora, mi sa che io preferisco uno script indipendente che puo' invocare Federico ma, meglio molto meglio se fattibile, invocato ogni x giorni da un cron

**Comment by phauly** [comment]
Il titolo potrebbe essere "Avere un modo per sapere per ogni tappa quanti e quali errori vengono fatti"

**Comment by phauly** [comment]
top!

**Comment by phauly** [comment]
mi piaceva che il metodo tornasse stampati prima le tappe con piu' errori, cosi' ci ho provato. Problema ho fatto la modifica su un mio file python (che leggeva il file .txt) e poi ho provato ad adattarlo al codice reale, potrei aver fatto degli errori. Purtroppo ad oggi non ho un deploy del codice (ne' un posto dove provare a far girare qualcosa da linea di comand). Eventualmente il codice che avevo io e' sotto.

Ho anche corretto un errore nelle stringhe di testo.

```
for tappa in d3:
    counter = collections.Counter(d3[tappa])
    d3[tappa] = (d3[tappa],{'counter':sum(counter.values())})

import collections

# from collections import OrderedDict

sorted_keys = sorted(d3, key=lambda tappa: d3[tappa][1]['counter'], reverse=True)

sorted_dict = OrderedDict()
for k in sorted_keys:
    sorted_dict[k] = d3[k]

for tappa in sorted_dict:
    counter = collections.Counter(d3[tappa][0])
    print(f'TAPPA = {tappa}')
    print(f'  ERRORI TOTALI = {sum(counter.values())}')
    for (error, freq) in counter.most_common(0):
        print(f'   ERRORE = {error}   (con frequenza = {freq})')
```

**Comment by phauly** [comment]
Pull request a https://github.com/kercos/HiSTORICCacciaAlTesoro/pull/34 

Non ho quasi mai usato git e quando lo provavo ad usare facevo sempre casino quindi dimmi pure se ho toppato in qualcosa ;)

**Comment by phauly** [comment]
Altre statistiche utili (specie per cacce permanenti per capire se alcune tappe vanno migliorate) sono:
 
* tempo medio per risolverla (ma anche min e max)
* numero di indizi richiesti
* tentativi sbagliati fatti (numero di errori)
* lista errori (questa e' gia' presente nel ticket in generale)
* ultima tappa in caso di abbandono

idea: uno script che controlla, per ogni tappa, se:

* se tempo medio (in ultima settimana) per risolverla > 1 minuto, ci manda warning (troppo difficile)
* se tempo medio (in ultima settimana) per risolverla < 10 secondi, ci manda warning (troppo facile)
* se numero di indizi richiesti (in ultimo mese) > 1.8, ci manda warning (troppo difficile)
* se numero di indizi richiesti (in ultimo mese) = 0, ci manda warning (troppo facile)
* se tentativi sbagliati fatti (numero di errori) > 5, ci manda warning (tappa che si presta a buttare risposte a caso)
* se tentativi sbagliati fatti (numero di errori) <0.1, ci manda warning (tappa troppo facile che quasi tutti azzeccano al primo tentativo)

@kercos

**Comment by kercos** [comment]
Semplificato questo issue su #98
