### ISSUE TITLE
Stato iniziale

### ISSUE THREAD

**Issue by kercos** [kercos/HiSTORICCacciaAlTesoro#69]
@phauly: l'immagine sopra e' legata a questo tuo messaggio. mi sembrava fantastico in teoria ma dopo aver fatto una caccia ho cambiato idea. PErche'? perche' appena finito ti dice che se vuoi fare una caccia puoi inserire la parola magica e quindi immagino che tanti (o almeno un 10%) reinseriscano la parola magica che gli abbiamo dato e che hanno usato all'inizio della caccia. in questo caso l'effetto sarebbe che ricominciano la caccia, probabilmente dopo un po' si accorgono che non era quello che volevano, rimangono li' a meta', magari ci scrivono per capire cosa fare ecc ecc. in generale una brutta esperienza utente. Tornerei a come era prima o discuterei di alternative (al momento a me non vengono in mente alternative, tutta questa parte non mi e' chiara in mente ;(

![telegram-cloud-photo-size-4-5913393041824134727-y](https://user-images.githubusercontent.com/2836492/121611225-c12e3900-ca92-11eb-9e78-592bea4be026.jpg)

**Comment by kercos** [comment]
Forse una soluzione alternativa sarebbe ridefinire lo stato iniziale con il messaggio di benvenuto e oltre ai tasti `switch language` e `info` aggiungere un nuovo pulsante `inizia una caccia`. Solo premendo quel pulsante si ha il messaggio "per inizare un caccia inserisci la parola magica", etc...

**Comment by phauly** [comment]
Mi sembra una soluzione fantastica! Molto lineare e sensata! io la voto al 100%!!!

**Comment by phauly** [comment]
Se ti va, sarebbe utile (per me) se provassi a dire come ti immagini la interfaccia!

Rispetto a ![image](https://user-images.githubusercontent.com/33067/121669225-66a1d680-caac-11eb-83c6-9fe91caacae9.png)

Il messaggio iniziale sarebbe solo qualcosa tipo "Ciao sono Nett1 :trident:, benvenuti in hiSTORIC! Potete usare i pulsanti sottostanti per interagire con me ;)"


Rispetto a [image](https://user-images.githubusercontent.com/33067/121669127-4b36cb80-caac-11eb-8807-2750265596b0.png)

Sopra agli altri bottoni e occupante due righe, aggiungere il bottone "Inizia una caccia al tesoro".

A quel punto potrebbe avere senso che ti esca la lista di cacce attive, tu ne clicchi su una e a quel punto ti chiede la parola chiave di quella caccia.

Gia' che ci siamo, pensiamo anche a questa cosa: per le cacce permanenti (ovvero sempre attive), ha senso che ci sia una parola chiave? Forse no. E se anche ci fosse dove se la va a cercare una persona (che magari scopre il fatto che esistono queste cacce grazie ad un totem o una vetrina in piazza duomo alle 23 e vuole provare a giocarci)? Ovvero ha senso che alcune cacce NON abbiano una parola chiave "segreta" ma chiunque le possa iniziare quando e come vuole (queste sarebbero le cacce permanenti, quelle per cui non c'e' un orario e NON le cacce per eventi che ha senso che abbiano un orario e un certo livello di risevatezza, pre-iscrizioni, ecc ecc)

----

Altra cosa (non legata al tema principale di questa issue): pensare se il bottone Info (con la i) venga rinominato in Aiuto (con il punto interrogativo)

**Comment by kercos** [comment]
In realtà non abbiamo ancora un criterio chiaro per distinguere cacce permanenti e non. Però anche se ce lo avessimo non so se sia prudente rivelare apertamente tutte le cacce disponibili. Mettiamo che ce ne siano 10 di disponibili, scorrere la lista crea un po' di confusione. A maggior ragione se devono comunque inserire la parola chiave è un passaggio in più un po' inutile.

Info è più un bottone per avere info su chi siamo. Mentre /aiuto è un comando per chiedere aiuto e può essere ridefinito all'interno di una caccia.

**Comment by phauly** [comment]
Rispondo separatemente. Il mio commento sopra andava nella direzione "in una caccia permanente, ha senso che ci sia una parola (segreta?) da inserire? al momento a me sembra di no. E se invece la risposta fosse si', dove pensiamo che la prendano le persone la parola (segreta?) per iniziare una specifica caccia?). Volendo possiamo spostare questa discussione in Trello visto che e' una cosa generica (e che coinvolge anche il progetto DOSS in generale)

**Comment by phauly** [comment]
> Info è più un bottone per avere info su chi siamo. Mentre /help è il comando per chiedere aiuto e può essere ridefinito all'interno di una caccia.
Riguardo a bottoni e comandi, anche qui non e' chiarissimo a me le potenzialita' e dove vogliamo andare. Avevo impressione che si volessero rimuovere i comandi per passare a soli bottoni (scrivere /qualcosa per una persona normale non e' proprio la cosa piu' user-friendly del mondo). sbaglio?

**Comment by kercos** [comment]
Secondo me ha comunque senso avere parola segreta per caccia permanente perché vogliamo evitare che le persone la attivino per sbaglio o "solo per provare" non trovandosi sul posto. Auspicabilmente una caccia permanente dovrebbe avere un totem fisico con istruzioni (con QR code e/o parola segreta).

**Comment by kercos** [comment]
Possiamo considerare di mettere sempre un comando HELP/AIUTO al posto o in aggiunta del comando /help durante la caccia.

**Comment by phauly** [comment]
> Secondo me ha comunque senso avere parola segreta per caccia permanente perché vogliamo evitare che le persone la attivino per sbaglio o "solo per provare" non trovandosi sul posto. Auspicabilmente una caccia permanente dovrebbe avere un totem fisico con istruzioni (con QR code e/o parola segreta).

Non ci avevo pensato e devo dire che hai ragione. Comunque ho aperto una scheda su trello (non la linko tanto e' privato) e credo abbia senso discuterne tutti insieme li'. Senza fretta!

**Comment by phauly** [comment]
> Possiamo considerare di mettere sempre un comando HELP/AIUTO al posto o in aggiunta del comando /help durante la caccia.

Non so se me lo hai gia' detto e ho scordato e neanche se c'e' gia' una issue per discutere la cosa, pero' secondo me e' una cosa da discutere. Ovvero, per cosa usiamo bottoni, per cosa usiamo comandi e anche, perche' usare comandi e non solo bottoni? Sposterei la conversazione in una issue a parte (a meno che non sia cortissima e bon) oppure addirittura su trello.

**Comment by phauly** [comment]
comunque questa issue e' in test e la ho testata e mi sembra ok.

ho accettato quindi la pull request 70
