### ISSUE TITLE
Capire perche' le stats non funzionano e sistemare

### ISSUE THREAD

**Issue by phauly** [kercos/HiSTORICCacciaAlTesoro#84]
![image](https://user-images.githubusercontent.com/33067/127210476-33bffe57-5013-420a-acdf-5c8f35df5da2.png)

Anche se ci sono squadre dentro la caccia, le stats dicono nessuna squadra iscritta

**Comment by kercos** [comment]
@phauly Ciao ho appena provato sia con "Caccia test Python" che con "Tutorial e 3 tappe" con due profile (da admin globale e admin di caccia) e in entrambi i casi riesco a vedere le stat (quando inizio la caccia da un altro account). Riusciresti ad essere un po' più specifico a come riprodurre il problema?

**Comment by kercos** [comment]
Risolto in v. 0.7.3
70f8802a3db5c0144241fe6f8110847974158c98
