### ISSUE TITLE
Aggiungere comando (per admin) che permette di scaricare tutte le foto e audio e video in uno zip

### ISSUE THREAD

**Issue by phauly** [kercos/HiSTORICCacciaAlTesoro#87]
Al momento lo puo' fare solo @kercos ma per alcune cacce sarebbe comodo se potessimo farlo anche noi in modo da passare agli organizzatori le foto e gli audio ecc

**Comment by kercos** [comment]
Di fatto lo potreste fare anche voi da codice se impostate il codice in locale. Sarebbe comunque utile aggiungere un modo per ottenere tutti i selfie direttamente dal bot per fare questa operazione. Per il momento se volete condividere qualche foto in particolare potete scaricarla direttamente da Airtable.
