### ISSUE TITLE
Cognome doppio

### ISSUE THREAD

**Issue by phauly** [kercos/HiSTORICCacciaAlTesoro#88]
Verificare perche' il cognome viene stampato due volte nelle varie notifiche a noi

Esempi (modificati per privacy)

New user: Roberto Chianti Chianti

Stats:
- Valentina Del Bin Del Bin Bibanesi 9/11 Finished=False

**Comment by kercos** [comment]
questo dovrebbe essere risolto con #89

**Comment by kercos** [comment]
Pensavo fosse risolto ma ho visto di nuovo questo errore:
![image](https://user-images.githubusercontent.com/2836492/131202888-5427c068-b492-43f9-a40e-1fbc0faee2d6.png)
