### ISSUE TITLE
Capire se un "backslash underscore" nel nome utente crea casini

### ISSUE THREAD

**Issue by phauly** [kercos/HiSTORICCacciaAlTesoro#89]
Oppure il backslash lo aggiunge il tuo codice quando stampa?

Esempio

New user: Goliath @Goliath\_24

**Comment by kercos** [comment]
fixed in v. 0.7.4
![image](https://user-images.githubusercontent.com/2836492/130796543-687af836-85b7-4d67-8f7b-99dc3e241961.png)
